name: CI
'on':
  push:
    branches:
      - master
      - testing
  pull_request:
    branches:
      - master
  workflow_dispatch: null
jobs:
  zig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh zig
      - name: Run one container
        run: ./run-container.sh zig
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: public/results/**/*zig.json
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh rust
      - name: Run one container
        run: ./run-container.sh rust
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: public/results/**/*rust.json
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh go
      - name: Run one container
        run: ./run-container.sh go
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: public/results/**/*go.json
  nim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh nim
      - name: Run one container
        run: ./run-container.sh nim
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: public/results/**/*nim.json
  elixir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh elixir
      - name: Run one container
        run: ./run-container.sh elixir
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: public/results/**/*elixir.json
  commit_results:
    runs-on: ubuntu-latest
    needs:
      - zig
      - rust
      - go
      - nim
      - elixir
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: results
          path: public/results/
      - name: Configurate git
        run: |-
          git config --global user.name 'Benchmark bot'
                    git config --global user.email 'your-username@users.noreply.github.com'
                    git config pull.rebase false
                  
      - name: Commit results
        run: |-
          git add ./public/results
                    git commit -m "Benchmark result update"
                    while ! git push; do git pull; done
                  
  deploy:
    runs-on: ubuntu-latest
    needs:
      - commit_results
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run predeploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
