name: CI
'on':
  push:
    branches:
      - master
      - testing
  pull_request:
    branches:
      - master
  workflow_dispatch: null
jobs:
  zig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh zig
      - name: Run one container
        run: ./run-container.sh zig
      - name: Configurate git
        run: |-
          git config --global user.name 'zig bot'
                      git config --global user.email 'your-username@users.noreply.github.com'
                      git config pull.rebase false
                    
      - name: Commit results
        run: |-
          git add ./results
                      git commit -m "Results update for zig"
                      while ! git push; do git pull; done
                    
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh rust
      - name: Run one container
        run: ./run-container.sh rust
      - name: Configurate git
        run: |-
          git config --global user.name 'rust bot'
                      git config --global user.email 'your-username@users.noreply.github.com'
                      git config pull.rebase false
                    
      - name: Commit results
        run: |-
          git add ./results
                      git commit -m "Results update for rust"
                      while ! git push; do git pull; done
                    
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh go
      - name: Run one container
        run: ./run-container.sh go
      - name: Configurate git
        run: |-
          git config --global user.name 'go bot'
                      git config --global user.email 'your-username@users.noreply.github.com'
                      git config pull.rebase false
                    
      - name: Commit results
        run: |-
          git add ./results
                      git commit -m "Results update for go"
                      while ! git push; do git pull; done
                    
  nim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh nim
      - name: Run one container
        run: ./run-container.sh nim
      - name: Configurate git
        run: |-
          git config --global user.name 'nim bot'
                      git config --global user.email 'your-username@users.noreply.github.com'
                      git config pull.rebase false
                    
      - name: Commit results
        run: |-
          git add ./results
                      git commit -m "Results update for nim"
                      while ! git push; do git pull; done
                    
  elixir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh elixir
      - name: Run one container
        run: ./run-container.sh elixir
      - name: Configurate git
        run: |-
          git config --global user.name 'elixir bot'
                      git config --global user.email 'your-username@users.noreply.github.com'
                      git config pull.rebase false
                    
      - name: Commit results
        run: |-
          git add ./results
                      git commit -m "Results update for elixir"
                      while ! git push; do git pull; done
                    
