name: CI
'on':
  push:
    branches:
      - master
      - testing
  pull_request:
    branches:
      - master
  workflow_dispatch: null
jobs:
  zig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh zig
      - name: Run one container
        run: ./run-container.sh zig
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh rust
      - name: Run one container
        run: ./run-container.sh rust
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh go
      - name: Run one container
        run: ./run-container.sh go
  nim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh nim
      - name: Run one container
        run: ./run-container.sh nim
  elixir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: ./build-docker.sh elixir
      - name: Run one container
        run: ./run-container.sh elixir
